name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use local deps
      run: tool/use_local_deps
    - name: Presubmit checks
      run: tool/presubmit
